### ISSUE TITLE
Deploy locally 

### ISSUE THREAD

**Issue by faierbol** [junngo/instagram#1]
Hi there, i think that your script is very good.
Can you please guide me thru on how to deploy it locally. Thank you in advanced.
PS: My env: Mac OS High Sierra 10:13

**Comment by junngo** [comment]
I gonna try deploy it locally. Asap, I gonna write how to deploy it.

**Comment by faierbol** [comment]
Thank you and maybe you can try adding a marketplace feature also :)

**Comment by junngo** [comment]
Deploy it locally.

A. Backend
1. git clone [gitAddress]
2. pipenv --three
2-1. If you not install pipenv -> sudo pip3 install pipenv
3. install DB
3-1 sudo apt-get install postgresql
3-2 psql -h 127.0.0.1 -U postgres template1
3-3 enter postgres db and CREATE DATABASE [yourDbName];
3-3 move settings/base.py and revise info -> DATABASES = {[yourDbName]}
4. pipenv shell
5. pipenv install -r requirements/base.txt
6. pipenv install -r requirements/local.txt
7. python manage.py makemigrations
8. python manage.py migrate
9. python manage.py runserver

B. Frontend
1. cd frontend
2. yarn install
3. mkdir .env
4. vi .env => write => NODE_PATH=src
5. yarn start
or
You should make new folder
1. create-react-app frontend
2. you should copy needed component to new fronted dir.

Thank you :)

**Comment by faierbol** [comment]
Hi @junngo,
I will give it a try today. Thanks a lot.
Regarding the marketplace ( classifieds) feature, did you thought about it?

**Comment by faierbol** [comment]
I want to build something similar to offerup.com or letgo.com but with instagram look and feel :)

**Comment by junngo** [comment]
I'm considering this function(marketplace). But I'm not make it this project. I try make it to another project. Thank you for your good idea :)
